site_name: Documentation for the lab
site_url: https://thelab.com
theme:
  features:
    - content.code.copy
    - navigation.tabs
    - toc.follow
  name: material
  icon:
    # https://fontawesome.com/search
    # https://simpleicons.org/
    # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#using-icons
    tag:
      kubernetes: simple/kubernetes
      metallb: simple/awselasticloadbalancing
      networking:  material/ip-network
      ingress: simple/ingress
      traefik: simple/traefikproxy
  font:
    text: Roboto
    code: Red Hat Mono
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: light blue
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

extra:
  tags:
    Kubernetes: kubernetes
    MetalLB: metallb
    Networking: networking
    Traefik: traefik
    Ingress: ingress

plugins:
  - glightbox
  - tags:
      enabled: true

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
      title: On this page
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details